### PR TITLE
empty filter check

### LINKED ISSUE #200: oa_fetch works with author_id as NULL
I ran code as below

author_works <- oa_fetch(
    entity = "works",
    author.id = author_id, 
    publication_year = publication_year,
    verbose = TRUE
}

It the author_id is null, the oa_fetch will fetch all the records for that year. e.g For year 2022. it did 

"Requesting url: https://api.openalex.org/works?filter=publication_year%3A2022
Getting 44486 pages of results with a total of 8897078 records...  "

Shall this case be taken care of ?  Maybe throw an exception?

### PR DESCRIPTION
**Pull request by yjunechoe**
Fixes #200 

`oa_query()` now errors if it receives a filter with a missing value, instead of silently ignoring it. Guards against users accidentally specifying a filter that ends up not doing anything.

```r
author_id <- NULL
author_works <- oa_fetch(
  entity = "works",
  author.id = author_id,
  publication_year = 2022,
  verbose = TRUE
)
#> Error: Filters must have a value: author.id
```

### CODE REVIEW

File: R/oa_fetch.R [hunk 1]
```diff
@@ -547,6 +547,16 @@ oa_query <- function(filter = NULL,
   entity <- match.arg(entity, oa_entities())
   filter <- c(filter, list(...))
 
+  empty_filters <- which(lengths(filter) == 0)
+  if (length(empty_filters) > 0) {
+    filter <- filter[-empty_filters]
+    stop(
+      "Filters must have a value: ",
+      paste(names(empty_filters), collapse = ","),
```
Comment (trangdata) [inline R/oa_fetch.R:555]:
```suggestion
      paste(names(empty_filters), collapse = ", "),
```

**Review by trangdata — APPROVED** [review]
Thank you for this PR! I made a small suggestion.

File: R/oa_fetch.R (hunk 1 above)
Comment (yjunechoe) [reply R/oa_fetch.R]: Added - thanks!
